title: Amal Das S.K
email: ask@amaldassk.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ask@amaldassk.com
github_username:  ask@amaldassk.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
port: 2020
host: 10.20.2.162
sass:
  style: compressed
  sass_dir: css
collections:
  my_collection:
    output: true
assets:
  compress:
    css: true
    js: true
  autowrite: true
  autoprefixer:
    browsers:
      - last 2 versions
      - IE > 9
  cache: .asset-cache
  cache_type: filesystem
  cdn: 'https://cdn.example.com'
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: /assets
  digest: true
  assets:
    - '*.png'
    - bundle.css
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
  features:
    liquid: true
    integrity: false
    automatic_img_size: true
    automatic_img_alt: true
